{% set name = "spatialist" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1cab6d2106d2fd151ae48a8de289cd05f36cabb4c4b762010864f587395dd84

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - dill
    - gdal >=2.4
    - geopandas
    - libspatialite >5.0.0
    - matplotlib-base
    - numpy
    - pandas
    - pathos >=0.2
    - progressbar2
    - python >={{ python_min }}
    - pyyaml
    - setuptools_scm
    - shapely
    - sqlite
    - tblib

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - spatialist
  commands:
    - pip check

about:
  home: https://github.com/johntruckenbrodt/spatialist
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python module for spatial data handling

  description: |
    This package offers functionalities for user-friendly geo data processing using GDAL and OGR.
  doc_url: https://spatialist.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/spatialist

extra:
  recipe-maintainers:
    - johntruckenbrodt
