{% set name = "spatialist" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90e5f87b26df4c3ed58895ff5fadf38cce53a6a3eb97ca5d5c1f2f26df781f4d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - progressbar2
    - matplotlib-base
    - pathos >=0.2
    - numpy <2.0
    - tblib
    - pyyaml
    - gdal >=2.4
    - sqlite
    - libspatialite >5.0.0
    - setuptools_scm
    - dill
    - shapely
    - pandas
    - geopandas

test:
  source_files:
    - spatialist/tests
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - spatialist
  commands:
    - pytest

about:
  home: https://github.com/johntruckenbrodt/spatialist
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python module for spatial data handling

  description: |
    This package offers functionalities for user-friendly geo data processing using GDAL and OGR.
  doc_url: https://spatialist.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/spatialist

extra:
  recipe-maintainers:
    - johntruckenbrodt
