{% set name = "spatialist" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f50652b0d26785b6e1c26a55f1f2f18fed7dd2483f734cec23e8b0169608951

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - progressbar2
    - matplotlib-base
    - pathos >=0.2
    - numpy <2.0
    - tblib
    - pyyaml
    - gdal >=2.4
    - sqlite
    - libspatialite >5.0.0
    - setuptools_scm
    - dill

test:
  source_files:
    - spatialist/tests
  requires:
    - pytest
  imports:
    - spatialist
  commands:
    - pytest

about:
  home: https://github.com/johntruckenbrodt/spatialist
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python module for spatial data handling

  description: |
    This package offers functionalities for user-friendly geo data processing using GDAL and OGR.
  doc_url: https://spatialist.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/spatialist

extra:
  recipe-maintainers:
    - johntruckenbrodt
